name: Dagger Pipeline for PR

on:
  pull_request:

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Python 3
        uses: actions/setup-python@v2
        with:
          python-version: "3.10.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install dagger-io

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run Dagger
        run: |
          python .ci/run_dagger_pull_request.py