name: Docker Image CI

on:
  push:
    branches:
      - main
    paths:
      - "docs/**"
      - "blog/**"
      - "i18n/**"
      - "Dockerfile"
      - "package.json"
      - "package-lock.json"
      - "yarn.lock"
      - "docusaurus.config.js"
      - "src/**"
      - "static/**"
      - ".github/workflows/**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
      with:
        image: tonistiigi/binfmt:latest
        platforms: arm64,arm
      
    - name: Dockerhub Readme
      uses: ms-jpq/sync-dockerhub-readme@v1
      with:
        username: qjoly
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
        readme: ./README.md
        repository: "qjoly/thebidouilleurxyz"

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build and push
      uses: docker/build-push-action@v4
      with:
         context: .
         platforms: linux/amd64,linux/arm64
         push: true
         tags: qjoly/thebidouilleurxyz:latest
      
    - name: ntfy_action
      uses: NiNiyas/ntfy-action@v1.0.1
      with:
        title: "CI TheBidouilleur.xyz terminé"
        url: https://ntfy.thoughtless.eu
        topic: github_cicd
