name: Push to Github registry

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
     - uses: actions/checkout@v3
     
     - name: Set up QEMU
       uses: docker/setup-qemu-action@v2
       with:
        image: tonistiigi/binfmt:latest
        platforms: arm64,arm
        
     - name: Log in to the Container registry
       uses: docker/login-action@ec9cdf07d570632daeb912f5b2099cb9ec1d01e6
       with:
         registry: ghcr.io
         username: ${{ github.actor }}
         password: ${{ secrets.GITHUB_TOKEN }}
         
     - name: Set up Docker Buildx
       uses: docker/setup-buildx-action@v2

     - name: Build and push Docker image
       uses: docker/build-push-action@v4
       with:
         platforms: linux/amd64,linux/arm64
         context: .
         push: true
         tags: ghcr.io/qjoly/thebidouilleur.xyz
